"""
Train XGBoost judicialization model (Agent F).

Reads:  data/synthetic/claims_dataset.json   (generated by generator.py)
Writes: data/models/agent_f_xgboost.pkl

Usage:
    python data/synthetic/train_agent_f.py

Requirements: xgboost, scikit-learn, pandas, numpy, shap (all in requirements.txt)
"""
from __future__ import annotations

import json
import logging
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
from xgboost import XGBClassifier

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

DATASET_PATH = Path(__file__).parent / "claims_dataset.json"
MODEL_DIR = Path(__file__).parent.parent / "models"
MODEL_PATH = MODEL_DIR / "agent_f_xgboost.pkl"

FEATURE_NAMES = [
    "amount_norm",
    "prior_claims_count",
    "days_since_incident",
    "interaction_count",
    "proposal_rejected_before",
    "claim_type_RC",
    "claim_type_DPA",
    "claim_type_danys_propis",
    "risk_score",
    "channel_phone",
]


def load_dataset(path: Path) -> pd.DataFrame:
    claims = json.loads(path.read_text(encoding="utf-8"))
    rows = []
    for c in claims:
        hist = c.get("history", {})
        comp = c.get("compliance", {})
        gt = c.get("ground_truth", {})
        claim_type = c.get("claim_type", "")
        rows.append({
            "amount_norm": c["financials"]["amount_requested"] / 1_000_000,
            "prior_claims_count": hist.get("prior_claims_count", 0),
            "days_since_incident": hist.get("days_since_incident", 0),
            "interaction_count": hist.get("interaction_count", 1),
            "proposal_rejected_before": int(hist.get("proposal_rejected_before", False)),
            "claim_type_RC": int(claim_type == "RC"),
            "claim_type_DPA": int(claim_type == "DPA"),
            "claim_type_danys_propis": int(claim_type == "danys_propis"),
            "risk_score": comp.get("fraud_score", 0),
            "channel_phone": int(c.get("channel", "") == "phone"),
            "judicializado": int(gt.get("judicializado", False)),
        })
    return pd.DataFrame(rows)


def train(df: pd.DataFrame) -> XGBClassifier:
    X = df[FEATURE_NAMES].values
    y = df["judicializado"].values

    pos_rate = y.mean()
    logger.info("Dataset: %d samples, %.1f%% judicializado", len(y), pos_rate * 100)

    scale_pos_weight = (1 - pos_rate) / pos_rate if pos_rate > 0 else 1.0

    model = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=scale_pos_weight,
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1,
    )

    # Cross-validation
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(model, X, y, cv=cv, scoring="roc_auc")
    logger.info("CV ROC-AUC: %.3f ± %.3f", cv_scores.mean(), cv_scores.std())

    # Final fit on full dataset
    model.fit(X, y)

    # Train / test split for reporting
    X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
    model_report = XGBClassifier(
        n_estimators=200, max_depth=4, learning_rate=0.05,
        subsample=0.8, colsample_bytree=0.8,
        scale_pos_weight=scale_pos_weight,
        eval_metric="logloss", random_state=42, n_jobs=-1,
    )
    model_report.fit(X_tr, y_tr)
    y_pred = model_report.predict(X_te)
    y_prob = model_report.predict_proba(X_te)[:, 1]

    logger.info("Hold-out classification report:\n%s", classification_report(y_te, y_pred))
    if len(np.unique(y_te)) > 1:
        logger.info("Hold-out ROC-AUC: %.3f", roc_auc_score(y_te, y_prob))

    # Feature importance
    importance = dict(zip(FEATURE_NAMES, model.feature_importances_))
    logger.info("Feature importances:")
    for feat, imp in sorted(importance.items(), key=lambda x: -x[1]):
        logger.info("  %-35s %.4f", feat, imp)

    return model


def main() -> None:
    if not DATASET_PATH.exists():
        logger.error("Dataset not found: %s — run generator.py first", DATASET_PATH)
        return

    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    df = load_dataset(DATASET_PATH)
    model = train(df)

    with MODEL_PATH.open("wb") as fh:
        pickle.dump(model, fh)

    logger.info("Model saved to %s", MODEL_PATH)

    # Quick SHAP summary (optional)
    try:
        import shap
        X = df[FEATURE_NAMES].values
        explainer = shap.TreeExplainer(model)
        shap_values = explainer.shap_values(X)
        mean_abs = np.abs(shap_values).mean(axis=0)
        logger.info("SHAP mean |values|:")
        for feat, val in sorted(zip(FEATURE_NAMES, mean_abs), key=lambda x: -x[1]):
            logger.info("  %-35s %.4f", feat, val)
    except Exception as exc:
        logger.info("SHAP summary skipped: %s", exc)


if __name__ == "__main__":
    main()
